[workspace]

members = [
    "design_patterns",
    "strategy",
    "observer",
    "decorator",
    "factory_method",
    "abstract_factory",
    "command",
    "adapter",
    "proxy",
    "bridge",
    "template_method",
    "composit",
    "visitor",
    "flyweight",
]